Fix build on debian 7
On debian 7, we run into:
...
dwz.c: In function ‘read_dwarf’:
dwz.c:10211:34: error: ‘SHF_COMPRESSED’ undeclared
...

Glibc defines SHF_COMPRESSED starting v2.22, and libelf has a fallback
definition starting v0.166, which are both not present here.

Fix this by adding a fallback definition in dwz.c.

2019-07-09  Tom de Vries  <tdevries@suse.de>

	* dwz.c (SHF_COMPRESSED): Define if not defined.