[testsuite] Fix tcl error in dwz-tests.exp
When running:
...
$ make check CC="clang -gdwarf-5"
...
I run into:
...
ERROR: tcl error sourcing testsuite/dwz.tests/dwz-tests.exp.
ERROR: 2
readelf: Warning: DIE at offset 0xe6 refers to abbreviation number 8 \
  which does not exist while executing
"exec readelf -wi min | grep DW_AT_name | grep -c / "
...

Fix this by wrapping the exec in a catch.

2021-02-09  Tom de Vries  <tdevries@suse.de>

	* testsuite/dwz.tests/dwz-tests.exp: Wrap "exec readelf" in catch.